---
- name: Install Apache and services
  hosts: all
  become: true

  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable Apache mod_rewrite
      apache2_module:
        name: rewrite
        state: present

    - name: Configure vhosts for FileGator
      template:
        src: filegator_vhost.conf.j2
        dest: /etc/apache2/sites-available/filegator.conf
      notify: restart apache

    - name: Configure vhosts for FreshRSS
      template:
        src: freshrss_vhost.conf.j2
        dest: /etc/apache2/sites-available/freshrss.conf
      notify: restart apache

    - name: Configure vhosts for GLPI
      template:
        src: glpi_vhost.conf.j2
        dest: /etc/apache2/sites-available/glpi.conf
      notify: restart apache

    - name: Configure vhosts for Nextcloud
      template:
        src: nextcloud_vhost.conf.j2
        dest: /etc/apache2/sites-available/nextcloud.conf
      notify: restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
