---
- name: Install Docker services
  hosts: all
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_facts.os.family == "Debian"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run Nginx Proxy Manager container
      docker_container:
        name: nginx-proxy-manager
        image: jc21/nginx-proxy-manager:latest
        ports:
          - "80:80"
          - "443:443"
        restart_policy: always

    - name: Run WordPress container
      docker_container:
        name: wordpress
        image: wordpress:latest
        ports:
          - "8010:80"
        restart_policy: always

    - name: Run Vaultwarden container
      docker_container:
        name: vaultwarden
        image: vaultwarden/server:latest
        ports:
          - "8050:80"
        restart_policy: always

    - name: Run Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - "9000:9000"
        restart_policy: always
